apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"frontend"},"name":"webapp-service","namespace":"default"},"spec":{"ports":[{"port":80,"protocol":"TCP","targetPort":80}],"selector":{"app":"frontend"},"type":"LoadBalancer"}}
  creationTimestamp: "2026-01-18T02:50:42Z"
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  labels:
    app: frontend
  name: webapp-service
  namespace: default
  resourceVersion: "4473"
  uid: cb631cf7-8db2-4d8b-80cb-e0806b1cef02
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 100.67.248.163
  clusterIPs:
  - 100.67.248.163
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30336
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: frontend
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - hostname: acb631cf78db24d8b80cbe0806b1cef0-413917644.us-east-1.elb.amazonaws.com
